### ISSUE TITLE
CodeStyleIssue

### ISSUE THREAD

**Issue by Andy-UA** [vnavka/CoinsDiffusion#1]
https://github.com/vnavka/CoinsDiffusion/blob/master/CoinDiffusionVP/Models/AreaMap.cs
Make verification of input data in AreaMap constuctor.
Codestyle problems InitMapSize | new 
https://github.com/vnavka/CoinsDiffusion/blob/master/CoinDiffusionVP/Models/City.cs
Define coins ammount in Extern constant

**Comment by vnavka** [comment]
Done
